# Generated by Django 4.1.1 on 2022-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('date_created', models.DateField(auto_now=True)),
                ('how_it_looks', models.ImageField(upload_to='recipes/')),
            ],
        ),
    ]
